Introduction page
RahullRawat/MetaUI pull request #2
Opened 2022-01-29 13:28 UTC by RahullRawat

2022-01-29 16:54 UTC, VishalPatil18 requested changes
Just one fix. Apart from that everything looks super cool! Great work man 👍

2022-01-29 16:54 UTC, VishalPatil18 commented on introduction.html
> +					<iframe
**Fix:** Here there's an unnecessary scroll. Can you fix that? It kinda disturbs the flow of scrolling the page down.

2022-01-30 04:23 UTC, VishalPatil18 approved these changes

2022-01-30 09:39 UTC, Abhijeet43 approved these changes
Code looks good

2022-01-30 10:01 UTC, merged